### ISSUE TITLE
Error in directive lang bind hook

### ISSUE THREAD

**Issue by zpwebbear** [leonardovilarinho/vue-multilanguage#10]
[Vue warn]: Error in directive lang bind hook: "TypeError: Cannot read property 'facebookSignIn' of undefined"
```
import MultiLanguage from 'vue-multilanguage';
import messages from './localization/i18n';

Vue.use(MultiLanguage, messages)
......
<p v-lang.facebookSignIn></p>
```

**Comment by leonardovilarinho** [comment]
Probably your language object does not have the facebookSignIn property. The error is not in the plugin, but rather is being used.

**Comment by zpwebbear** [comment]
I can use this property by translate method, like 
`return this.translate(this.$language, 'facebookSignIn',) and it's work. But v-lang directive look's more comfortable! What I doing wrong?
