### ISSUE TITLE
demo does not work

### ISSUE THREAD

**Issue by mvanroon** [leonardovilarinho/vue-multilanguage#14]
The demo application is giving all sorts of errors.

I cd'ed into the demo folder, did `npm install` and `npm run dev` but I'm getting a ton of JS errors.

![schermafbeelding 2017-06-26 om 13 43 00](https://user-images.githubusercontent.com/1309448/27537741-68410a2a-5a75-11e7-8c83-c56224e48cd9.png)

**Comment by leonardovilarinho** [comment]
Hello, I tried to replicate the error and I could not, here it is normal, try again.

Thanks for the feedback.

**Comment by mvanroon** [comment]
Ah I installed vue-multilangue using npm, but the [latest version published to npm is 2.0.2](https://www.npmjs.com/package/vue-multilanguage)

**Comment by leonardovilarinho** [comment]
Wow man, sorry.. I not publish new version, now the 2.1.1 version can install from npm
