### ISSUE TITLE
default language is not being picked up

### ISSUE THREAD

**Issue by mvanroon** [leonardovilarinho/vue-multilanguage#15]
See code below. Language is always being set to 'nl' because my browser is Dutch.
I can't seem to force the default language.

also I've tried setting this.$language to 'en' in of my component, but this too does not seem to work

main.js:

````
import VueMultiLanguage from 'vue-multilanguage'

Vue.use(VueMultiLanguage, {
  default: 'en',
  en: {
    title: 'Hello',
    welcome: 'Welcome, {name}'
  },
  nl: {
    title: 'Olá',
    welcome: 'Bem-vindo, {name}'
  }
})
````

Component.vue:

````
<template>
  <div class="component">
    <h1 v-lang.title></h1>
  </div>
</template>
````

**Comment by leonardovilarinho** [comment]
This error also has not been reproduced here, when changing the default language works normally, check again if you can not show prints.

**Comment by mvanroon** [comment]
See https://github.com/leonardovilarinho/vue-multilanguage/issues/14#issuecomment-311430291
