### ISSUE TITLE
Can't use capitals in language names

### ISSUE THREAD

**Issue by Epro95Z28** [leonardovilarinho/vue-multilanguage#17]
The following works fine

```
import MultiLanguage from 'vue-multilanguage'
import Vue from 'vue'
import en_us from '@/internationalization/en_US/en_US.json'
import fr_ca from '@/internationalization/ca_FR/ca_FR.json'

Vue.use(MultiLanguage, {
    default: 'fr_ca',
    en_us,
    fr_ca
})
```
This does not work

```
import MultiLanguage from 'vue-multilanguage'
import Vue from 'vue'
import en_US from '@/internationalization/en_US/en_US.json'
import fr_ca from '@/internationalization/ca_FR/ca_FR.json'

Vue.use(MultiLanguage, {
    default: 'en_US ',
    en_US,
    fr_ca
})
```

**Comment by leonardovilarinho** [comment]
Your default language no exists in scope inserted.

Enviado do meu telefone Windows 10

De: Epro95Z28<mailto:notifications@github.com>
Enviado:quarta-feira, 26 de julho de 2017 11:48
Para: leonardovilarinho/vue-multilanguage<mailto:vue-multilanguage@noreply.github.com>
Cc:Subscribed<mailto:subscribed@noreply.github.com>
Assunto: [leonardovilarinho/vue-multilanguage] Can't use capitals in language names (#17)


The following works fine

import MultiLanguage from 'vue-multilanguage'
import Vue from 'vue'
import en_us from '@/internationalization/en_US/en_US.json'
import fr_ca from '@/internationalization/ca_FR/ca_FR.json'

Vue.use(MultiLanguage, {
    default: 'fr_ca',
    en_us,
    fr_ca
})


This does not work

import MultiLanguage from 'vue-multilanguage'
import Vue from 'vue'
import en_US from '@/internationalization/en_US/en_US.json'
import fr_ca from '@/internationalization/ca_FR/ca_FR.json'

Vue.use(MultiLanguage, {
    default: 'fx',
    en_US,
    fr_ca
})

**Comment by leonardovilarinho** [comment]
The plugin accept only lowercase languages.

**Comment by leonardovilarinho** [comment]
assa


Att, Leonardo Vilarinho
Analista de sistemas pelo Instituto Federal do Triângulo Mineiro
