### ISSUE TITLE
dist folder not in npm package

### ISSUE THREAD

**Issue by cobaltway** [leonardovilarinho/vue-multilanguage#18]
In your package, the main file of the library is referenced as `"dist/vue-multilanguage.js"`, which is supposedly a ready-to-use babelified file.

However, your dist folder is listed in your .npmignore file, so its not there when downloading your library with npm... So:

1. This probably won't work:
`import MultiLanguage from 'vue-multilanguage'`

2. You obligate people using webpack to make a special exception for the library when they are using babel-loader (as usually it does not re-compile files from node_modules).

**Comment by leonardovilarinho** [comment]
Hi, I can not see this.

In the repostory there is no directory called dist, much less the .npmignore.

**Comment by cobaltway** [comment]
Look at your package.json, field main. Also look at your gitignore and npmignore (included in the version published on npm only). If there is no dist folder, you should correct at least the package.json.

But you definitely should include a compiled version of your library and reference it as main. Please look at [this recommendations](https://stackoverflow.com/a/45299835/3548338).
