### ISSUE TITLE
Does every component have to listen to a language-changed event ?

### ISSUE THREAD

**Issue by jdriesen** [leonardovilarinho/vue-multilanguage#2]
Hi,

First of all, thanks for this great component.
I was able to implement it (almost) successfully in my SPA.

I will explain the 'almost' part...
Let's say, my SPA contains 3 components
Component 1: a header with a language selector. (contains 2 buttons, one for each language)
Component 2: my main menu
Component 3: the content 

When changing the language in my language selector (clicking a button), I'm performing the 
 _**this.$language = <the_new_language>**_
function, and everything is working fine (I'm immediately seeing the translated text in the 'language selector component)

But, also my component 2 and component 3 are containing language dependent items (e.g. my menu-items in component 2 should be translated as well)
And this is currently not working...

Now, one solution I see is that I 'broadcast' (emit) a language-changed event (as soon as a language button is clicked), 
Every component can listen (via the **_on_** statement) to this event.
Is this the way to go ?
Or is there an other, probably better approach ?

Thanks in advance for your answer,

Johnny Driesen
Belgium

**Comment by leonardovilarinho** [comment]
@jdriesen 

thanks for the feedback.

For now the only way to fix this is by communicating components, I'm researching a solution to this, among them are:

- Use localStorage to store the current language, when changing it the page will be reloaded with the new language. But the Vuex data is lost.

- Use Vuex to store the current language, so changes occur on all components. However the Vuex will be obligatory.

If you choose one of these options I can change the plugin to meet the need.

But so far I'm looking for a better solution.

**Comment by jdriesen** [comment]
Thanks for your feedback, Leonardo.

Got it working with 'communication between components'. 
- using an 'emit' when changing the language in my header
- using an 'on' in every component.

It's working super fine !
(currently, I don't need Vuex in my APP, so that's why I didn't choose that option)

Currently, I'm using your solution as 
<span v-lang.hi></span>

But is there a way I can use it in the data() function of a component ?

(PS.: once I've a cleaned-up solution, I'll make it available online)  

Thanks again for your feedback & the great work !

Grtz,
Johnny 
(Belgium)

**Comment by leonardovilarinho** [comment]
I have corrected this problem :fire: -> af148c187e4cc8ddc08c98afae1e0627401c7c9d

I used a recursive function that goes through all the components and change their language.

To test run npm update

About using in date () I could not understand, open a new problem with this, please :)
