### ISSUE TITLE
translate() method not working.

### ISSUE THREAD

**Issue by kamgasimo** [leonardovilarinho/vue-multilanguage#25]
I'm getting the following errors in the console when i try to use the method:

-Error in render function: "TypeError: Cannot read property 'indexOf' of undefined"
-TypeError: Cannot read property 'indexOf' of undefined

**Comment by leonardovilarinho** [comment]
Please, show me your code.

**Comment by kamgasimo** [comment]
I returned `this.translate('login')` from a computed property.

import MultiLanguage from 'vue-multilanguage'

    Vue.use(MultiLanguage, {
        default: 'en',
	     en: {
	    	login: 'Login'
	    },
	    fr: {
		login: 'S\'identifier'
	    },
    })

**Comment by leonardovilarinho** [comment]
Your code work for me, see follow image. Please, update your package.json to version 3.x of vue-multilanguage. 

![Code works!](https://image.prntscr.com/image/6fmq592xRDeInrzWB3xBmQ.png)

**Comment by kamgasimo** [comment]
I updated to vue-multilanguage 3.0.3 but the translation stopped working at-all.
The value of vue-lang in the localStorage is 'fr' but `this.language` is returning 'en'

**Comment by leonardovilarinho** [comment]
I fix this problem in 8cc43b1.

Please, update your package to 3.0.4 version, the storage is automatic in current version.

**Comment by kamgasimo** [comment]
Great!!! It's seems to work perfectly now.
