### ISSUE TITLE
can't use v-if on a components using v-lang

### ISSUE THREAD

**Issue by kamgasimo** [leonardovilarinho/vue-multilanguage#26]
`<div v-if="!loading" v-lang.login>Login</div>` 
The above condition won't work because of the presence of `v-lang` but `v-show` does.

**Comment by leonardovilarinho** [comment]
This `div' is your root element from component? If yes, you not can use `v-if` in root element.

I try:

```html
<template>
  <div id="app">
    <button @click="language = 'fr'">To FR</button>
    <button @click="language = 'en'">To EN</button>
    <button @click="loading = !loading">Toggle loading</button>

    <h1 v-if="!loading" v-lang.login></h1>
  </div>
</template>
```

And work perfectly.

**Comment by kamgasimo** [comment]
it's not the root element
