### ISSUE TITLE
Language changing to default after page refresh

### ISSUE THREAD

**Issue by ashcslmn** [leonardovilarinho/vue-multilanguage#27]
I've used the stand-alone installation of vue-multilanguage and followed the demo folder from the repository but i cannot get the language to stay on the chosen language after page refresh.

//.vue
`changeLangJP() {
      this.language = 'jp'
      window.localStorage.setItem('vue-lang', this.language)
    },
    changeLangEN() {
      this.language = 'en'
      window.localStorage.setItem('vue-lang', this.language)
    }`

Is there something I missed out?

**Comment by leonardovilarinho** [comment]
I fix this problem in 8cc43b1.

Please, update your package to 3.0.4 version, the storage is automatic in current version.
