### ISSUE TITLE
v-bind and v-lang

### ISSUE THREAD

**Issue by vanbogaertjonas** [leonardovilarinho/vue-multilanguage#28]
I'm unable to bind  "v-lang" to an element in a v-for loop.
the value for v-lang should be equal to "item.name".
Is there a way to accomplish this? 

```
	<button (need v-lang bind here)  v-if="!item.disabled" v-for="item in items"  v-bind:id="item.image" v-bind:class="{ active: item.active }">
		{{ item.name }}
	</button>
```

**Comment by leonardovilarinho** [comment]
We have the `translate` method for it. Call `{{ translate(item.name` }}` for example.

Please, in next problem use right repository: https://github.com/leonardovilarinho/vue-acl
