### ISSUE TITLE
Compatibility with Vuetify

### ISSUE THREAD

**Issue by iec989** [leonardovilarinho/vue-multilanguage#29]
Hi there,

Congrats for the easy and clean solution mate.

I was trying to use vue-multilanguage with vuetify, and I'm finding some issues.

How can I integrate a translatiom within a v-text-field: https://vuetifyjs.com/components/forms ? My idea would be to use it where it says label=

Any ideas?

Thanks a million

**Comment by leonardovilarinho** [comment]
Hi,

Try use `:label="translate('path.to.string')"`, this can works.

**Comment by iec989** [comment]
Thank you, that worked perfectly well.

I also got a "required" translation, which contains "field" as a parameter.

If I do the below, it works fine:
`<p v-lang.required="{field: translate('name')}"></p>`

However, when I try to do `this.translate('required', "sample"),`, it ignores the second parameter, any idea why?

Thanks!
