### ISSUE TITLE
Using your solution in the data() function

### ISSUE THREAD

**Issue by jdriesen** [leonardovilarinho/vue-multilanguage#3]
Hi,

I'll try to be a bit more clear...

In a Vue Component, we can have a data() function

data() : {
 return {
    title: 'this is the title'
  }
}

As you know, one can refer to 'title ' in the template using double curly braces.

Now, I'm wondering if '**this is a title**' can be translated using your solution...

Grtz,
Johnny

**Comment by leonardovilarinho** [comment]
I arranged this in commit 3cd26df

Use this method to do this:
```
computed: {
    youAttribute() {
        return this.translate(this.$language, 'path.to.msg', objectWithParams)
    }
}
```

Note that I used computed properties, because it would be better for this type of data. See the VueJS documentation.

Thanks for reporting more.

**Comment by jdriesen** [comment]
Super Support !!

Thank you.

Kind regards,

Johnny
