### ISSUE TITLE
Is it possible to include html elements in the translations?

### ISSUE THREAD

**Issue by iec989** [leonardovilarinho/vue-multilanguage#34]
If I have a translation with `"I agree on the <a href="/termsandconditions"> Terms&Conditions </a>"`

It will be printed as text. 

Is there any way I can force it to be written as HTML code?

Thanks

**Comment by leonardovilarinho** [comment]
You can create a computed property calling `this.translate('...')` method, and in your element use `v-html` for compile the html code (`<footer v-html="computedProperty"></footer>`)
