### ISSUE TITLE
List of available Languages

### ISSUE THREAD

**Issue by CrazyAlien1** [leonardovilarinho/vue-multilanguage#35]
Is there a way to get all the available languages we placed when initializing  the Plugin?
Wanted to populate a list so the user can choose.

**Comment by leonardovilarinho** [comment]
Hello, you can make a method why get same object sent to plugin, and use `for..in` to show the languages. For example:

main.js
```javascript
import languages from './language-file'

Vue.prototype.$getLanguagensList = () => {
    let languages_name = []
    for(const name in languages)
        if(name != 'default')
            languages_name.push(lang)

   return languages_name
}
...
```

your-component.vue
```html
<li v-for="lang in $getLanguagensList()"> {{lang}} </li>
```
