### ISSUE TITLE
How can I use Vue Multilanguage in a default function of a props?

### ISSUE THREAD

**Issue by jackrsantana** [leonardovilarinho/vue-multilanguage#36]
I would like to use vue-multilanguage in a default function of a props:
![chrome_2018-02-16_13-59-48](https://user-images.githubusercontent.com/16987558/36316589-d8ad5bb4-1321-11e8-871a-4e2689080d6c.png)

However, it is giving the following error:
![phpstorm64_2018-02-16_14-00-02](https://user-images.githubusercontent.com/16987558/36316607-e500858a-1321-11e8-9047-1900f776f368.png)

Thank you in advance.

**Comment by pirsplus** [comment]
This will work as expected

```js

  // ...

  computed: {
    default () {
      return this.translate('welcome', 'Vue.JS')
    }
  }

````

**Comment by leonardovilarinho** [comment]
It isn't possible, on try access `this` in `icon` object the javascript search this method in own object. Try make with computed properties.
