### ISSUE TITLE
How works the translation?

### ISSUE THREAD

**Issue by jtpdev** [leonardovilarinho/vue-multilanguage#37]
I don't undertood how works the translation! 'Cause in localhost the language is portuguese, but in my host online the language that is showed is english.

The showed language is the host language?

Must be set the language to show in page by javascript in the module knews the language to use?

I saw in line 27, that must be set by the browser.

**Comment by leonardovilarinho** [comment]
If you defined a default language, he is used. Else this plugin use the language defined in `lang` DOM attribute. In last case is retrieved language from operacional system.
