### ISSUE TITLE
how to use on placeholder in input tag

### ISSUE THREAD

**Issue by m-alinasab** [leonardovilarinho/vue-multilanguage#38]
hi .

i want set multilanguage on placeholder on input tag .
how to use ?

thanks .

**Comment by leonardovilarinho** [comment]
Hello, use the `translate` method. For example `<input :placeholder="translate('...')*/>`

**Comment by m-alinasab** [comment]
and use with this method : 
<div>`trans.name` , `trans.hi`</div>
?

**Comment by leonardovilarinho** [comment]
Hi, I not understanded. You can use:

`<input :placeholder="translate('path.to.string.translated') />"`

or

`<div v-lang.path.to.string.translated></div>`
