### ISSUE TITLE
Using the same parameter multiple times

### ISSUE THREAD

**Issue by jeppebemad** [leonardovilarinho/vue-multilanguage#41]
Trying to use the same parameter twice in a translation, only the first slot is replaced. The second is not.
Is this intended behavior?

Thanks for a great module!

**Comment by jaumebalust** [comment]
@jeppebemad  what do you mean?

**Comment by leonardovilarinho** [comment]
@jeppebemad  thank you for say it,

I understand, and this plugin yet not support replace all variables, I have little time, so I go change it soon. This issue is in line 122, the replacement should have /g regex.

**Comment by leonardovilarinho** [comment]
I rewrote the plugin, to give more performance and improve usage. In this new version (> 4) I applied its issue.

If you want to continue in version 3, send a PR with the correction, because at the moment I can not dedicate to this. Or you can create a mixin to replace the translate method
