### ISSUE TITLE
this.translate() with parameter

### ISSUE THREAD

**Issue by CrazyAlien1** [leonardovilarinho/vue-multilanguage#43]
Hi I'm doing a form validation
and was going through every property of an object and just making a basic validation whether it was empty or not. and wanted to add to a translation the name of the property that corresponds to the name of the field.

    export default {
        data: function() {
            return {
                image: undefined,
                info: {
                    name: '',
                    description: '',
                    dish: '',
                    phone: '',
                    skype: '',
                    email: '',
                    languages: [],
                    payment: [],
                    imageData: ""  // we will store base64 format of image in this string
                },
                error: {
                    name: undefined,
                    description: undefined,
                    dish: undefined,
                    phone: undefined,
                    skype: undefined,
                    email: undefined,
                    languages: undefined,
                    payment: undefined,
                    imageData: undefined
                },
            }
        },
        methods: {

            finalizeHost(){
                //Small validation...
                let foundErrors = true;
                for (var prop in this.info) {
                    if (this.info.hasOwnProperty(prop)) {
                        if(this.info[prop] === '' || this.info[prop] === undefined)
                        {
                            **_console.log(this.translate('emptyField', prop));
                            this.error[prop] = this.translate('emptyField', prop);_**
                            foundErrors = true;
                        }else{
                            this.error[prop] = undefined;
                        }
                    }
                }
                if(foundErrors){
                    return;
                }
            }
    }

It translates but the {field} doesn't change it displays "{field}, cannot be empty" 

if I put in the template the component `<p v-lang.fieldEmpty="{name: 'Name'}"></p>` it works.

Is this only possible inside computed?

**Comment by leonardovilarinho** [comment]
Hello,

your message `emptyField` in translate js file is like `emptyField: 'The {name} field is empty'`? With {name} annotation?

If yes, you need to pass an object to `translate` method e.g `this.translate('emptyField', {name: 'age'})`, so the message is translated to `The age field is empty`.

To simplify this, in your case, you can transform your message to `emptyField: 'The {0} field is empty'`, so you can pass only the value to `translate` method, e.g: `this.translate('emptyField', 'age')`, and get the same result.
