### ISSUE TITLE
Multiline

### ISSUE THREAD

**Issue by magned86** [leonardovilarinho/vue-multilanguage#45]
Hello~!!
I am stuck at making multiline contents.
<br> and &lt;br&gt; is not working.

For example,
1. script
...
en: {
  hi: 'Hello,<br>My name is Jay.'
}
2. template
<p v-lang.hi></p>

And, the result should be as follows:
Hello,
My name is Jay.

Please give some help.

**Comment by boomsya** [comment]
my solution:
```
export default {
	default: "uk",
	uk: {
            lang_my_insurance_seniority: "Мій страховий<br/>стаж"
         }
}
```

to use with translated parameter to component:
`<rounded-button :text="this.translate('lang_my_insurance_seniority')" />`
and in component output this: `<div v-html="text"></div>`

think this works too: `<div v-html="this.translate('lang_my_insurance_seniority')"></div>`

**Comment by magned86** [comment]
I didn't think about the v-html. Thanks it works.
