### ISSUE TITLE
Change Mixin to use property other than language

### ISSUE THREAD

**Issue by garrensweet** [leonardovilarinho/vue-multilanguage#46]
Right now the Mixin from this plugin provides `language` as a property for every component that is registered in Vue. There are so many other components out there that require the `language` property, that this plugin breaks them.

I'm suggesting that we rename the `language` property to something more specific and private, like `multilanguage` to avoid collision with the -- at least -- dozens of other components that utilize a `language` property. Thoughts?

**Comment by leonardovilarinho** [comment]
Hi @garrensweet 

this is in my to-do list, I will be rewriting the plugin with a new version, because when I wrote I was starting in the area.

**Comment by leonardovilarinho** [comment]
I rewrote the plugin, to give more performance and improve usage. In this new version (> 4) I applied its issue.
