### ISSUE TITLE
get languages list

### ISSUE THREAD

**Issue by boomsya** [leonardovilarinho/vue-multilanguage#47]
hi. i try to include your lib to my project
i have question: how can i get list of languages?

example:
```
export default {
	default: 'ua',
	test1: {
		hi: 'Olá',
		welcome: 'Bem-vindo, {name}'
	},
	test2: {
		hi: 'Hello',
		welcome: 'Welcome, {name}'
	},
	test3: {

	}
}
```
my project  contain several .vue files used as components

**Comment by leonardovilarinho** [comment]
Hi @boomsya 

I will add this in a new version, I am rewriting the plugin, from version 4 will be available.

**Comment by boomsya** [comment]
close
