### ISSUE TITLE
JSON or JS for translations

### ISSUE THREAD

**Issue by jdriesen** [leonardovilarinho/vue-multilanguage#5]
Hi Leonardo,

Just a small question.
Your readme files is giving us the advice to use JSON, but your example is using separate JS files.

Which solution would you recommend ?

Thanks in advance for your answer,

Johnny

**Comment by leonardovilarinho** [comment]
Strange, GitHub should be showing you old readme.

I recently released version 2 of the plugin, in it we can only use js objects, json was deprecated, because it had a bad performance.

**Comment by jdriesen** [comment]
Yep, I'm still seeing the old readme....
See this printscreen... taken on April 18th...

![SJON readme](http://www.driesen.eu/insiderclub/translation.png)

**Comment by leonardovilarinho** [comment]
I understand, now we use javascript objects and no more json, `{name}` we see there are parameters of the message, that is, you can send a `name` variable to replace this value.
