### ISSUE TITLE
Problem with language changing with a lot of components

### ISSUE THREAD

**Issue by Aohler** [leonardovilarinho/vue-multilanguage#50]
Hello, 

I am currently on a website with lots of components and I added a switch language button on my Nav Bar. The architecture is like this : 

App.vue
```
<vue-router></vue-router>
```

The vue router calls "/" which is Home.vue, it possesses the NavBar

```
<template>
  <nav-bar />
</template>
```

And the navBar contains the FlagButton (switch language button)

```
<template>
  <flag-button/>
</template>
```

The flag button is in charge to change the language and I added the click like this : 
```
@click="$ml.change(nextLang)"
```

It works, I can see it changes the language, but it stops at the nav-bar : Impossible to update the text on the Home.vue component.
Moreover, it doesn't changes the localStorage variable : when I refresh the page it comes back to the initial language.

I thought I could resolve this issue by using : 
```
"$emit(nextLang)" 
```
but it doesn't seems to work and isn't a good way of programming.

From what I understood by reading the module, $ml is not global but uses global variables. So I don't really understand why I have this issue. They should all be listening to the "_vueEBus2" that is a global variable but it doesn't seems like this is the case.

So  it would be nice if you had some solution or modifications of your module that could solve this problem,

Thank you in advance for your reply

**Comment by leonardovilarinho** [comment]
Fix in 3.x version or later
