### ISSUE TITLE
Misprint in the description (and MLBuilder doesn't work?)

### ISSUE THREAD

**Issue by MikhailMelnikovNsk** [leonardovilarinho/vue-multilanguage#51]
![1](https://user-images.githubusercontent.com/40119987/41192473-5e95e98a-6c28-11e8-9742-738f2d1df1e2.jpg)

And

```
<p v-text="$ml.get('myMessage')" />

computed: {
    myMessage () {
      return new MLBuilder('msg').with('f', this.friends).with('l', 406)
    }
  }
```

doesn't work? reading not from computed 'myMessage '...

**Comment by leonardovilarinho** [comment]
Hi, your local message should have `ml` prefix, e.g: `mlMyMessage` and `<p v-text="$ml.get('MyMessage')" />`.

**Comment by MikhailMelnikovNsk** [comment]
Hi, ok.

But in the example - https://github.com/leonardovilarinho/vue-multilanguage/blob/master/example/src/App.vue

![2](https://user-images.githubusercontent.com/40119987/41199041-f5342f00-6cb4-11e8-97b4-d912ed1ad65d.jpg)
