### ISSUE TITLE
How to import $ml to router.js file?

### ISSUE THREAD

**Issue by MikhailMelnikovNsk** [leonardovilarinho/vue-multilanguage#52]
For different page titles.

title: $ml.get('pageTitle')
title: this.$ml.get('pageTitle')

Doesn't work ('$ml' is not defined)

**Comment by leonardovilarinho** [comment]
Hi, this pluhin work only inside vue components. To set page title you can use `vue-head` plugin or `document.title = this.$ml.get('pageTitle')` in your mounted method.

**Comment by kamgasimo** [comment]
To use the plugin out of a component I do the following
`import Vue from 'vue'`
  `const vm = new Vue()`
  `const $ml = vm.$ml`

Then you can use

`title: $ml.get('pageTitle') `

Make sure you have imported ml plugin in your entry file (eg. main.js) as started in the doc.
And make sure you don't execute this code before the ML plugin is been used by Vue.
