### ISSUE TITLE
'with' is not working.

### ISSUE THREAD

**Issue by dvvdev** [leonardovilarinho/vue-multilanguage#55]
Hello! Thanks for your hard work on this module.

In the demo Vue, there is this line: 
h1 v-text="$ml.**with('leo').get('title')**"

I wasn't sure if 'leo' is a string or an object, but either way, 

I am making a store with 'Add Product, Add Category' etc.

h2 v-text="$ml.get('add')" returns Add
h2 v-text="$ml.get('prod')" returns Product

h2 v-text="$ml.**with('prod').get('add')**" returns Add

Can you provide some insight to how the with key works in the example from the demo?

**Comment by leonardovilarinho** [comment]
For one parameter e.g `You have {0} friends`, use `$ml.with('four').get('msg')`.

For more parameters e.g `{name}, you have num} friends`, use `$ml.with('num', 'four').with('name', 'Jesus').get('msg')`.
