### ISSUE TITLE
new version > previous version ? 

### ISSUE THREAD

**Issue by mercs600** [leonardovilarinho/vue-multilanguage#59]
Hi @leonardovilarinho thanks for this plugin. I was using this with previous version. Now I see that API was changed. I saw your comments that this version has better performance. Could you explain briefly what was wrong with performance in older version and how did you improve it ? 

To be honest, no offense, I really liked your previous version with much simple API. But still I would like to use this plugin because the size is much smaller than  for eg. vue-i18n.

**Comment by leonardovilarinho** [comment]
Hi,

the previous version walks each component updating the language, each components has an locale language.

In new version I used the Event Bus for centralize the language in a local, and this make a batter performance.

**Comment by mercs600** [comment]
Hi @leonardovilarinho, thanks for your explaining and your solution ;-)
