### ISSUE TITLE
Additional translations for component 

### ISSUE THREAD

**Issue by mercs600** [leonardovilarinho/vue-multilanguage#60]
Hello, I'm wondering if can I add some additional translations only for one component ? Now I have to use MLCreate on application level. What in case when I want to add some translation only for one component ? How can I achieve it ?

**Comment by leonardovilarinho** [comment]
Hellow @mercs600

Yes, you can use 3.x version for it (https://github.com/leonardovilarinho/vue-multilanguage/tree/v3.x)
