### ISSUE TITLE
Vue library doubled imported by vue-e-bus

### ISSUE THREAD

**Issue by mercs600** [leonardovilarinho/vue-multilanguage#62]
Hi @leonardovilarinho ✋ I just checked my vendor file because I saw that is too big. I noticed some weird thing: 
![Zrzut ekranu 2019-04-1 o 17 32 16](https://user-images.githubusercontent.com/7935392/55340117-54778700-54a4-11e9-88f9-eaf91faa97b3.png)

You can see that we have imported vue.esm.js twice :( 
1. Imported by my source files
2. Imported by your vue-e-bus dist files which is imported by vue-multilanguage. 

My question is - are you able to fix it ? I would like to use your src files in my application instead of dist.

**Comment by leonardovilarinho** [comment]
It was updated in version 4.0.8, thanks for the #63
