### ISSUE TITLE
Language getter or Vuex Store Language mutation?

### ISSUE THREAD

**Issue by BrilllianD** [leonardovilarinho/vue-multilanguage#65]
Hello. Thank for this usefull plugin.

Can you help me with this: 
I need subscribe to Language changing (getter) or change language in my vuex store by my code.

Thanks for help

**Comment by leonardovilarinho** [comment]
Hi, sorry for the delay. To do this use an observer to look at the current language value and then with each change update your vuex as well:

```
watch: {
	'$ml.current' (value) {
	   // submit value in vuex
	}
}
```

**Comment by BrilllianD** [comment]
Thanks, forget about this in JS
