### ISSUE TITLE
Current language is not changing

### ISSUE THREAD

**Issue by SerikK** [leonardovilarinho/vue-multilanguage#74]
Hi. I want to trigger current language.

currentLang() {
      return this.$ml.current;
    },

But it is staying unchanged

**Comment by leonardovilarinho** [comment]
Hi, sorry for the delay,
I was not able to replicate this behavior, here it is always updated. Can you give more details of your application? An example of the component tree? This may be related.

**Comment by SerikK** [comment]
After some times it worked using computed property
