### ISSUE TITLE
How to work with arrays?

### ISSUE THREAD

**Issue by Nastyaord** [leonardovilarinho/vue-multilanguage#75]
We have a select and we want to fill it with array of data. How can we do it?

If a write : 

new MLanguage('english').create({
        jobList: ['Nurse', 'Office work', 'Construction', 'Sport']
})

I had an error: 

"TypeError: db.replace is not a function"

Thanks

**Comment by leonardovilarinho** [comment]
Hi, sorry for delay. An example:

```
new MLanguage('english').create({
      fruits: ['Apple', 'Pineapple']
}),
```

In component:

```
<p v-text="$ml.get('fruits')[0]" />
```
