### ISSUE TITLE
How to change language on radio input change?

### ISSUE THREAD

**Issue by Momciloo** [leonardovilarinho/vue-multilanguage#8]
Hey! Thanks for the plugin! Everything is pretty straight forward. I managed to connect all of my elements with desired text values in `eng` language. Now I have a problem to change language. I have two radio inputs in header component that I want to use to toggle the currently active language.

```
<div class="header--lang">
    <label for="en" class="header--lang-item">
        <input @change="languageChange" id="en" name="language" value="en" type="radio">
        <span>En</span>
    </label>
    <label for="fr" class="header--lang-item">
        <input @change="languageChange" id="fr" name="language" value="fr" type="radio">
        <span>Fr</span>
    </label>
</div>
```

and i registred method `languageChange` to do this:
```
<script>
export default {
  data: function() {
    return {
      
    }
  },
  methods: {
    languageChange(e) {
      if (e.target.checked) {
        this.$language = '' + e.target.value;
        console.log(this.$language);
      }
    }
  }
}
</script>
```

And it turns out that I'm getting the right `this.$language` value in the console, but the text on the page doesn't change. 

I am constantly getting only text in the `en` language. If I remove `en` language from `main.js` `MultiLanguage`, I get "undefined" in console.

```
Vue.use(MultiLanguage, {
	en: {
    HOMETOPSECTIONTITLE: 'Lorem ipsum dummy text',
.
.
.
```

**Comment by leonardovilarinho** [comment]
By convention, you can only do the language switching on a component that uses the `v-lang` directive.

You can circumvent this by simply calling the dretive anywhere in the no-component, even if it is in an empty element.

**Comment by Momciloo** [comment]
Yes, I am doing that. But text is not changing. 😟 I have `v-lang.HOMETOPSECTIONTITLE` (for example) all across the platform. And it is connected to the value I defined in my `Vue.use(MultiLanguage, {` `en` object, but when I set `this.$language` to `fr`  it does not change text to my `fr` object that I also created right after `en` in the same `Vue.use(MultiLanguage, {`. And funny thing that I cannot have `Vue.use(MultiLanguage, {`  that does not contain `en`. For example, If i define `fr` &  `hu`, I'm getting console error:

```
    Uncaught TypeError: Cannot read property 'HOMETOPSECTIONTITLE' of undefined
    at MultiLanguage.relaunchByDirective (eval at <anonymous> (build.js:1519), <anonymous>:61:29)
    at bind (eval at <anonymous> (build.js:1519), <anonymous>:233:13)
    at callHook$1 (eval at <anonymous> (build.js:772), <anonymous>:5233:5)
    at _update (eval at <anonymous> (build.js:772), <anonymous>:5159:7)
    at Array.updateDirectives (eval at <anonymous> (build.js:772), <anonymous>:5140:5)
    at invokeCreateHooks (eval at <anonymous> (build.js:772), <anonymous>:4739:22)
    at createElm (eval at <anonymous> (build.js:772), <anonymous>:4633:11)
    at createChildren (eval at <anonymous> (build.js:772), <anonymous>:4723:9)
    at createElm (eval at <anonymous> (build.js:772), <anonymous>:4631:9)
    at createChildren (eval at <anonymous> (build.js:772), <anonymous>:4723:9)
```

**Comment by Momciloo** [comment]
Managed to make it work. Still not sure what was the issue, but I copied everything from demo folder and now it works. :D Thank you for a great plugin! :)
