### ISSUE TITLE
It doesn't work with IE

### ISSUE THREAD

**Issue by giovannigenna** [leonardovilarinho/vue-multilanguage#9]
I have try your plugin in IE, but it doesn't works.
In chrome it works right, but in IE I have this issue in console:
**_Error in directive lang bind hook: "ReferenceError: 'Symbol' is not defined_**

Someone know why that happens ?

Thanks
Giovanni

**Comment by adrianDragomir** [comment]
The plugin  does not even work on Ipad!

**Comment by leonardovilarinho** [comment]
Unfortunately I do not have the features to test and make it work on this browser and on that device.

**Comment by matthew-dean** [comment]
@giovannigenna @leonardovilarinho  This library uses `for..of` which automatically generates a `Symbol` polyfill for ES5 browsers if you compile with Babel. But since it generates a polyfill, not sure why IE would have a problem.

**Comment by dyaa** [comment]
The plugin re-written with es5 so please check the last commit.

The update still not published to `npm` 
 
waiting for @leonardovilarinho

**Comment by leonardovilarinho** [comment]
Updated in npm!

**Comment by jdriesen** [comment]
Hi @leonardovilarinho  & @dyaa 

Thanks for the NPM update !!!
It solved also the ES6 issue... [https://stackoverflow.com/questions/44287584/how-to-minify-es6-code-using-webpack](https://stackoverflow.com/questions/44287584/how-to-minify-es6-code-using-webpack)

Lost almost a complete day with it, but never mind... 
I'm happy it's solved !!

Grtz & keep on doing the good work,

Johnny (Belgium)
